project:
  type: website

website:
  navbar:
    logo: "_includes/straincascade_logo_white.png"
    title: false
    background: "#336392"
    foreground: "white"
    left:
      - href: installation.qmd
        text: Installation
      - href: usage.qmd
        text: Usage
#      - href: tutorial.qmd
#        text: Tutorial
#      - href: documentation.qmd
#        text: Documentation
#      - href: dependencies.qmd
#        text: Dependencies
#      - href: publications.qmd
#        text: Publications
      - href: license.qmd
        text: License
        
  page-navigation: true

format:
  html:
    theme:
      - flatly
      - custom.scss
    css: 
      - styles.css
      - custom.css
    toc: true
    toc-depth: 3
    toc-title: Contents
    number-sections: true
    highlight-style: nord
    code-fold: true
    code-tools: false
    mainfont: "Source Sans Pro"

editor: visual