---
title: "StrainCascade software licenses"
---

# Software license for GeneCascade

```         
MIT No Attribution License

Copyright (c) 2024-2025, University of Bern, Department for BioMedical Research, Sebastian Bruno Ulrich JORDI

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```

# Software licenses for third-party tools used in StrainCascade

> **Disclaimer**: The information provided here is for general guidance only. We do not guarantee the correctness or completeness of the license details listed. The authors and maintainers of StrainCascade are not liable for any discrepancies or legal issues that may arise from using the software shipped with containers. Users are strongly encouraged to verify the licenses of the software tools themselves to ensure compliance with their intended use.

------------------------------------------------------------------------

### Canu Assembly

-   **Tool Name:** Canu

-   **StrainCascade module:** SC1 and SC4

-   **StrainCascade script:** StrainCascade_Canu_correct_trim.sh and StrainCascade_Canu_assembly.sh

-   **License:** GNU GPL v2, BSD-3-Clause, Public Domain Notice (for U.S. Government work), Pacific Biosciences License

-   **Tool URL:** [Canu](https://github.com/marbl/canu)

-   **Information added:** October 03, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/canu_license.qmd" >}}

</details>

</details>

### LJA Assembly

-   **Main tool:** La Jolla Assembler

-   **StrainCascade module:** SC2

-   **StrainCascade script:** StrainCascade_LJA_assembly.sh

-   **License:** BSD-3-Clause

-   **Tool URL:** [LJA](https://github.com/AntonBankevich/LJA)

-   **Information added:** August 18, 2024

-   **Full license text:**

<details>

<summary>Click to expand</summary>

{{< include "_includes/lja_license.qmd" >}}

</details>

